packaging_format = 2

id = "paperless-ngx"
name = "Paperless-ngx"
description.en = "Scan, index and archive all your physical documents"
description.fr = "Scannez, triez et archivez tous vos documents papiers"

version = "2.6.3~ynh1"

maintainers = ["Tagada"]

[upstream]
license = "GPL-3.0-or-later"
website = "https://paperless-ngx.com"
demo = "https://demo.paperless-ngx.com/"
admindoc = "https://paperless-ngx.readthedocs.io/en/latest/index.html"
userdoc = "https://paperless-ngx.readthedocs.io/en/latest/usage_overview.html"
code = "https://github.com/paperless-ngx/paperless-ngx"
cpe = "???" # XXX: No CPE yet... check https://nvd.nist.gov/products/cpe/search/results?namingFormat=2.3&keyword=paperless

[integration]
yunohost = ">= 11.0.0"
architectures = "all"
multi_instance = true
ldap = false
sso = false
disk = "50M"
ram.build = "350M"
ram.runtime = "350M"

[install]
    [install.domain]
    # this is a generic question - ask strings are automatically handled by Yunohost's core
    type = "domain"
    full_domain = true

    [install.admin]
    # this is a generic question - ask strings are automatically handled by Yunohost's core
    type = "user"

    [install.admin_pw]
    ask.en = "Please chose a password for admin user."
    type = "password"

    [install.init_main_permission]
    type = "group"
    default = "all_users"

    [install.init_api_permission]
    ask.en = "Paperless-ngx API access list"
    type = "group"
    default = "visitors"

[resources]
    [resources.sources]

        [resources.sources.main]
        url = "https://github.com/paperless-ngx/paperless-ngx/releases/download/v2.6.3/paperless-ngx-v2.6.3.tar.xz"
        sha256 = "0c74c7d6ba35b576c47481021322d7f5e8847f89c489eed47f5399588aad6d19"

        autoupdate.strategy = "latest_github_release"
        autoupdate.asset = "paperless-ngx-.*.tar.xz"

        [resources.sources.gs]
        url = "https://github.com/ArtifexSoftware/ghostpdl-downloads/releases/download/gs10021/ghostpdl-10.02.1.tar.gz"
        sha256 = "25399af0ef5bb94f2a13c91dc785c128d14f16744c4c92fa7c86e011c23151d8"

    [resources.system_user]

    [resources.install_dir]

    [resources.data_dir]
    subdirs = ["consume", "data", "media", "imagemagick"]

    [resources.permissions]
    main.url = "/"
    main.auth_header = false

    api.url = "/api/"
    api.show_tile = false
    api.auth_header = false

    share.url = "/share/"
    share.show_tile = false
    share.auth_header = false
    share.protected = true
    share.allowed = "visitors"
    
    [resources.ports]
    main.default = 8095

    [resources.apt]
    packages = "python3, python3-pip, python3-dev, python3-venv, default-libmysqlclient-dev, fonts-liberation, imagemagick, gnupg, libpq-dev, libmagic-dev, mime-support, libzbar0, poppler-utils, unpaper, ghostscript, icc-profiles-free, liblept5, libxml2, pngquant, zlib1g, tesseract-ocr, libatlas-base-dev, libxslt1-dev, redis-server, pkg-config"

    [resources.database]
    type = "postgresql"
